config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "kittens#index"

  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(params_required)

    if @kitten.save
      flash[:notice] = "Nice, you created a new kitten!"
      redirect_to @kitten
    else
      flash[:alert] = "Maybe you forgot to put something."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(params_required)
      flash[:notice] = "Great, you changed the kitten!"
      redirect_to @kitten
    else
      flash[:alert] = "Oops, you forgot something needed to change the kitten."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    flash[:notice] = "Excellent, you destroyed a kitten."
    redirect_to root_path, status: :see_other
  end

  private

  def params_required
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten_form.html.erb
<%= form_with model: @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field(:name, placeholder: "Felix")%>
  <%= f.label :age %>
  <%= f.number_field(:age, in: 1..12, placeholder: 1) %>
  <%= f.label :cuteness %>
  <%= f.number_field(:cuteness, in: 1..10, placeholder: 5) %>
  <%= f.label :softness %>
  <%= f.number_field(:softness, in: 1..10, placeholder: 5) %>
  <%= f.submit "Submit kitten" %>
<% end %>

app/views/kittens/edit.html.erb
<%= render 'kitten_form' %>

<ul>
  <li><%= link_to "Destroy kitten", kitten_path(@kitten),
          data: { turbo_method: :delete,
                  turbo_confirm: "Are you sure?" } %>
  </li>
</ul>

app/views/kittens/index.html.erb
<h1>Kittens</h1>
<ul>
<% @kittens.each do |kitten| %>
  <li><%= link_to kitten.name, kitten_path(kitten) %>
      <%= link_to "Destroy kitten", kitten_path(kitten),
          data: { turbo_method: :delete,
                  turbo_confirm: "Are you sure?" } %>
  </li>
<% end %>
</ul>

app/views/kittens/new.html.erb
<%= render 'kitten_form' %>

app/views/kittens/show.html.erb
<h1>Kitten details</h1>
<p>Name: <%= @kitten.name%></p>
<p>Age: <%= @kitten.age%></p>
<p>Cuteness: <%= @kitten.cuteness%></p>
<p>Softness: <%= @kitten.softness%></p>

<ul>
  <li><%= link_to "Edit", edit_kitten_path(@kitten) %></li>
  <li><%= link_to "Destroy", kitten_path(@kitten),
          data: { turbo_method: :delete,
                  turbo_confirm: "Are you sure?" } %>
  </li>
</ul>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>